create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  trade_idea_id bigint unique,
  symbol text not null,
  timeframe text not null,
  exchange text not null,
  direction text not null,
  signal_json jsonb not null,
  status text not null default 'active',
  signal_fingerprint text,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.user_taken_trades (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  signal_id text not null,
  symbol text not null,
  timeframe text not null,
  exchange text not null default 'hyperliquid',
  direction text not null,
  entry_price numeric not null,
  stop_loss numeric not null,
  take_profit_1 numeric not null,
  take_profit_2 numeric not null,
  risk_reward numeric,
  setup_score numeric,
  confidence numeric,
  market_bias text,
  market_regime text,
  liquidity_status text,
  signal_timestamp timestamptz,
  status text not null default 'taken' check (status in ('taken', 'open', 'closed', 'tp_hit', 'sl_hit', 'cancelled')),
  result text not null default 'open' check (result in ('open', 'win', 'loss', 'closed', 'cancelled')),
  pnl numeric,
  created_at timestamptz not null default now(),
  taken_at timestamptz not null default now(),
  unique (user_id, signal_id)
);

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  source text not null,
  event text not null,
  payload_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.execution_logs (
  id bigint generated by default as identity primary key,
  signal_id text,
  symbol text,
  status text not null,
  reason text,
  payload_json jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.api_usage_logs (
  id bigint generated by default as identity primary key,
  route text not null,
  method text not null,
  client_ip text,
  status_code integer,
  created_at timestamptz not null default now()
);

alter table public.signals enable row level security;
alter table public.user_taken_trades enable row level security;
alter table public.webhook_events enable row level security;
alter table public.execution_logs enable row level security;
alter table public.api_usage_logs enable row level security;

create policy "Taken trades readable by owner"
  on public.user_taken_trades for select
  using (auth.uid() = user_id);

create policy "Taken trades insertable by owner"
  on public.user_taken_trades for insert
  with check (auth.uid() = user_id);

create policy "Taken trades updatable by owner"
  on public.user_taken_trades for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Taken trades deletable by owner"
  on public.user_taken_trades for delete
  using (auth.uid() = user_id);

create index if not exists signals_created_idx on public.signals (created_at desc);
create index if not exists signals_symbol_idx on public.signals (symbol);
create index if not exists signals_fingerprint_idx on public.signals (signal_fingerprint);
create index if not exists user_taken_trades_user_taken_idx on public.user_taken_trades (user_id, taken_at desc);
create index if not exists webhook_events_created_idx on public.webhook_events (created_at desc);
create index if not exists execution_logs_created_idx on public.execution_logs (created_at desc);
create index if not exists api_usage_logs_route_idx on public.api_usage_logs (route, created_at desc);
