from __future__ import annotations

from datetime import UTC, datetime
import secrets

from fastapi import APIRouter, Header, HTTPException, Query, status

from app.config import get_settings
from app.forex.models import (
    ACTIVE_FOREX_STATUSES,
    TERMINAL_FOREX_STATUSES,
    ForexOverview,
    ForexSignalList,
    ForexSignalPlan,
    ForexScanRunResult,
    TakeTradePreparation,
    TakeTradeRequest,
)
from app.forex.news import forex_news_risk
from app.forex.scanner import forex_pair_infos, scan_forex
from app.forex.sessions import forex_session_state
from app.forex.storage import get_signal, list_signals, save_trade_preparation

router = APIRouter()


def _require_internal_secret(x_internal_api_secret: str | None) -> None:
    expected = get_settings().internal_api_secret
    if not expected or not x_internal_api_secret or not secrets.compare_digest(expected, x_internal_api_secret):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Scanner access denied.")


def _require_authenticated(authorization: str | None) -> None:
    if not authorization or not authorization.lower().startswith("bearer ") or len(authorization) < 24:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Authentication required.")


@router.get("/forex/pairs")
async def forex_pairs():
    return {"market_type": "forex", "pairs": forex_pair_infos()}


@router.get("/forex/sessions")
async def forex_sessions():
    return forex_session_state()


@router.get("/forex/overview", response_model=ForexOverview)
async def forex_overview():
    settings = get_settings()
    session = forex_session_state()
    news_risk, news_reason = forex_news_risk()
    active = list_signals(ACTIVE_FOREX_STATUSES, limit=5)
    configured = bool(settings.twelve_data_api_key)
    if not configured:
        message = "Forex data provider is not configured."
    elif not active:
        message = "No persisted Forex setup currently meets the scanner criteria."
    else:
        message = None
    return ForexOverview(
        configured=configured,
        provider="twelvedata",
        active_session=session,
        supported_pairs=forex_pair_infos(),
        news_risk_warning=news_reason if news_risk != "LOW" else "News risk: LOW.",
        top_setups=active,
        message=message,
    )


@router.get("/forex/signals", response_model=ForexSignalList)
async def forex_signals(
    status_filter: str | None = Query(default=None, alias="status"),
    limit: int = Query(default=100, ge=1, le=500),
):
    statuses = (
        tuple(item.strip().upper() for item in status_filter.split(",") if item.strip())
        if status_filter
        else None
    )
    signals = list_signals(statuses, limit)
    return ForexSignalList(signals=signals, count=len(signals))


@router.get("/forex/signals/{signal_id}", response_model=ForexSignalPlan)
async def forex_signal_detail(signal_id: str):
    signal = get_signal(signal_id)
    if signal is None:
        raise HTTPException(status_code=404, detail="Forex signal not found.")
    return signal


@router.post("/forex/scanner/run", response_model=ForexScanRunResult)
async def forex_scanner_run(x_internal_api_secret: str | None = Header(default=None)):
    _require_internal_secret(x_internal_api_secret)
    return await scan_forex()


@router.post("/forex/scan")
async def deprecated_forex_scan():
    raise HTTPException(
        status_code=410,
        detail="Interactive scanning is disabled. Forex signals are generated by the scheduled scanner.",
    )


@router.post("/forex/signals/{signal_id}/take-trade", response_model=TakeTradePreparation)
async def take_forex_trade(
    signal_id: str,
    payload: TakeTradeRequest,
    authorization: str | None = Header(default=None),
):
    _require_authenticated(authorization)
    signal = get_signal(signal_id)
    if signal is None:
        raise HTTPException(status_code=404, detail="Forex signal not found.")
    if signal.status in TERMINAL_FOREX_STATUSES or signal.direction == "WAIT":
        raise HTTPException(status_code=409, detail="This Forex signal is no longer eligible to take.")
    stop_distance = abs(signal.entry_price - signal.stop_loss)
    if stop_distance <= 0:
        raise HTTPException(status_code=409, detail="This signal has invalid risk levels.")
    risk_amount = payload.account_balance * payload.risk_percentage / 100
    position_size = risk_amount / stop_distance
    save_trade_preparation(
        signal,
        user_id=None,
        account_balance=payload.account_balance,
        risk_percentage=payload.risk_percentage,
        risk_amount=risk_amount,
        position_size=position_size,
        execution_method=payload.execution_method,
    )
    return TakeTradePreparation(
        signal=signal,
        account_balance=payload.account_balance,
        risk_percentage=payload.risk_percentage,
        risk_amount=round(risk_amount, 2),
        stop_distance=stop_distance,
        position_size=round(position_size, 4),
        execution_method=payload.execution_method,
        prepared_at=datetime.now(UTC),
    )
